/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentRegistry {
  export type AlphaInfoStruct = {
    name: string;
    pitchStyle: string;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AlphaInfoStructOutput = [
    name: string,
    pitchStyle: string,
    active: boolean,
    registeredAt: bigint
  ] & {
    name: string;
    pitchStyle: string;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "alphaAddresses"
      | "alphaAgents"
      | "deactivateAlpha"
      | "getAllAlphas"
      | "getAlphaCount"
      | "getSubscriptions"
      | "isSubscribed"
      | "owner"
      | "registerAlpha"
      | "subscribe"
      | "transferOwnership"
      | "unsubscribe"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlphaDeactivated"
      | "AlphaRegistered"
      | "Subscribed"
      | "Unsubscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "alphaAddresses",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "alphaAgents",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAlpha",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAlphas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAlphaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubscribed",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAlpha",
    values: [AddressLike, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "alphaAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "alphaAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAlpha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAlphas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAlphaCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubscribed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAlpha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;
}

export namespace AlphaDeactivatedEvent {
  export type InputTuple = [alpha: AddressLike];
  export type OutputTuple = [alpha: string];
  export interface OutputObject {
    alpha: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AlphaRegisteredEvent {
  export type InputTuple = [alpha: AddressLike, name: string];
  export type OutputTuple = [alpha: string, name: string];
  export interface OutputObject {
    alpha: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [subscriber: AddressLike, alpha: AddressLike];
  export type OutputTuple = [subscriber: string, alpha: string];
  export interface OutputObject {
    subscriber: string;
    alpha: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnsubscribedEvent {
  export type InputTuple = [subscriber: AddressLike, alpha: AddressLike];
  export type OutputTuple = [subscriber: string, alpha: string];
  export interface OutputObject {
    subscriber: string;
    alpha: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  alphaAddresses: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  alphaAgents: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        pitchStyle: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  deactivateAlpha: TypedContractMethod<
    [alpha: AddressLike],
    [void],
    "nonpayable"
  >;

  getAllAlphas: TypedContractMethod<
    [],
    [
      [string[], AgentRegistry.AlphaInfoStructOutput[]] & {
        addrs: string[];
        infos: AgentRegistry.AlphaInfoStructOutput[];
      }
    ],
    "view"
  >;

  getAlphaCount: TypedContractMethod<[], [bigint], "view">;

  getSubscriptions: TypedContractMethod<
    [beta: AddressLike],
    [string[]],
    "view"
  >;

  isSubscribed: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAlpha: TypedContractMethod<
    [alpha: AddressLike, name: string, pitchStyle: string],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[alpha: AddressLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unsubscribe: TypedContractMethod<[alpha: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "alphaAddresses"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "alphaAgents"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, string, boolean, bigint] & {
        name: string;
        pitchStyle: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deactivateAlpha"
  ): TypedContractMethod<[alpha: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllAlphas"
  ): TypedContractMethod<
    [],
    [
      [string[], AgentRegistry.AlphaInfoStructOutput[]] & {
        addrs: string[];
        infos: AgentRegistry.AlphaInfoStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAlphaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSubscriptions"
  ): TypedContractMethod<[beta: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isSubscribed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAlpha"
  ): TypedContractMethod<
    [alpha: AddressLike, name: string, pitchStyle: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[alpha: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsubscribe"
  ): TypedContractMethod<[alpha: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AlphaDeactivated"
  ): TypedContractEvent<
    AlphaDeactivatedEvent.InputTuple,
    AlphaDeactivatedEvent.OutputTuple,
    AlphaDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AlphaRegistered"
  ): TypedContractEvent<
    AlphaRegisteredEvent.InputTuple,
    AlphaRegisteredEvent.OutputTuple,
    AlphaRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "Unsubscribed"
  ): TypedContractEvent<
    UnsubscribedEvent.InputTuple,
    UnsubscribedEvent.OutputTuple,
    UnsubscribedEvent.OutputObject
  >;

  filters: {
    "AlphaDeactivated(address)": TypedContractEvent<
      AlphaDeactivatedEvent.InputTuple,
      AlphaDeactivatedEvent.OutputTuple,
      AlphaDeactivatedEvent.OutputObject
    >;
    AlphaDeactivated: TypedContractEvent<
      AlphaDeactivatedEvent.InputTuple,
      AlphaDeactivatedEvent.OutputTuple,
      AlphaDeactivatedEvent.OutputObject
    >;

    "AlphaRegistered(address,string)": TypedContractEvent<
      AlphaRegisteredEvent.InputTuple,
      AlphaRegisteredEvent.OutputTuple,
      AlphaRegisteredEvent.OutputObject
    >;
    AlphaRegistered: TypedContractEvent<
      AlphaRegisteredEvent.InputTuple,
      AlphaRegisteredEvent.OutputTuple,
      AlphaRegisteredEvent.OutputObject
    >;

    "Subscribed(address,address)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "Unsubscribed(address,address)": TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;
    Unsubscribed: TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;
  };
}
