/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AgentRegistry {
  export type AlphaInfoStruct = {
    agentId: BytesLike;
    name: string;
    pitchStyle: string;
    feeAddress: AddressLike;
    active: boolean;
    registeredAt: BigNumberish;
  };

  export type AlphaInfoStructOutput = [
    agentId: string,
    name: string,
    pitchStyle: string,
    feeAddress: string,
    active: boolean,
    registeredAt: bigint
  ] & {
    agentId: string;
    name: string;
    pitchStyle: string;
    feeAddress: string;
    active: boolean;
    registeredAt: bigint;
  };
}

export interface AgentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "alphaAgents"
      | "alphaIds"
      | "deactivateAlpha"
      | "getAllAlphas"
      | "getAlphaCount"
      | "getFeeAddress"
      | "getSubscriptions"
      | "isSubscribed"
      | "owner"
      | "registerAlpha"
      | "subscribe"
      | "transferOwnership"
      | "unsubscribe"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AlphaDeactivated"
      | "AlphaRegistered"
      | "Subscribed"
      | "Unsubscribed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "alphaAgents",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "alphaIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateAlpha",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllAlphas",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAlphaCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFeeAddress",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscriptions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isSubscribed",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerAlpha",
    values: [BytesLike, string, string, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "subscribe",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unsubscribe",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "alphaAgents",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "alphaIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deactivateAlpha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllAlphas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAlphaCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeeAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isSubscribed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAlpha",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "subscribe", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unsubscribe",
    data: BytesLike
  ): Result;
}

export namespace AlphaDeactivatedEvent {
  export type InputTuple = [agentId: BytesLike];
  export type OutputTuple = [agentId: string];
  export interface OutputObject {
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AlphaRegisteredEvent {
  export type InputTuple = [
    agentId: BytesLike,
    name: string,
    feeAddress: AddressLike
  ];
  export type OutputTuple = [agentId: string, name: string, feeAddress: string];
  export interface OutputObject {
    agentId: string;
    name: string;
    feeAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscribedEvent {
  export type InputTuple = [subscriber: AddressLike, agentId: BytesLike];
  export type OutputTuple = [subscriber: string, agentId: string];
  export interface OutputObject {
    subscriber: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnsubscribedEvent {
  export type InputTuple = [subscriber: AddressLike, agentId: BytesLike];
  export type OutputTuple = [subscriber: string, agentId: string];
  export interface OutputObject {
    subscriber: string;
    agentId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AgentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AgentRegistry;
  waitForDeployment(): Promise<this>;

  interface: AgentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  alphaAgents: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean, bigint] & {
        agentId: string;
        name: string;
        pitchStyle: string;
        feeAddress: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;

  alphaIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  deactivateAlpha: TypedContractMethod<
    [agentId: BytesLike],
    [void],
    "nonpayable"
  >;

  getAllAlphas: TypedContractMethod<
    [],
    [
      [string[], AgentRegistry.AlphaInfoStructOutput[]] & {
        ids: string[];
        infos: AgentRegistry.AlphaInfoStructOutput[];
      }
    ],
    "view"
  >;

  getAlphaCount: TypedContractMethod<[], [bigint], "view">;

  getFeeAddress: TypedContractMethod<[agentId: BytesLike], [string], "view">;

  getSubscriptions: TypedContractMethod<
    [subscriber: AddressLike],
    [string[]],
    "view"
  >;

  isSubscribed: TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerAlpha: TypedContractMethod<
    [
      agentId: BytesLike,
      name: string,
      pitchStyle: string,
      feeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  subscribe: TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unsubscribe: TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "alphaAgents"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, boolean, bigint] & {
        agentId: string;
        name: string;
        pitchStyle: string;
        feeAddress: string;
        active: boolean;
        registeredAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "alphaIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "deactivateAlpha"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getAllAlphas"
  ): TypedContractMethod<
    [],
    [
      [string[], AgentRegistry.AlphaInfoStructOutput[]] & {
        ids: string[];
        infos: AgentRegistry.AlphaInfoStructOutput[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAlphaCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeeAddress"
  ): TypedContractMethod<[agentId: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getSubscriptions"
  ): TypedContractMethod<[subscriber: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isSubscribed"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerAlpha"
  ): TypedContractMethod<
    [
      agentId: BytesLike,
      name: string,
      pitchStyle: string,
      feeAddress: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subscribe"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unsubscribe"
  ): TypedContractMethod<[agentId: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AlphaDeactivated"
  ): TypedContractEvent<
    AlphaDeactivatedEvent.InputTuple,
    AlphaDeactivatedEvent.OutputTuple,
    AlphaDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "AlphaRegistered"
  ): TypedContractEvent<
    AlphaRegisteredEvent.InputTuple,
    AlphaRegisteredEvent.OutputTuple,
    AlphaRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "Subscribed"
  ): TypedContractEvent<
    SubscribedEvent.InputTuple,
    SubscribedEvent.OutputTuple,
    SubscribedEvent.OutputObject
  >;
  getEvent(
    key: "Unsubscribed"
  ): TypedContractEvent<
    UnsubscribedEvent.InputTuple,
    UnsubscribedEvent.OutputTuple,
    UnsubscribedEvent.OutputObject
  >;

  filters: {
    "AlphaDeactivated(bytes32)": TypedContractEvent<
      AlphaDeactivatedEvent.InputTuple,
      AlphaDeactivatedEvent.OutputTuple,
      AlphaDeactivatedEvent.OutputObject
    >;
    AlphaDeactivated: TypedContractEvent<
      AlphaDeactivatedEvent.InputTuple,
      AlphaDeactivatedEvent.OutputTuple,
      AlphaDeactivatedEvent.OutputObject
    >;

    "AlphaRegistered(bytes32,string,address)": TypedContractEvent<
      AlphaRegisteredEvent.InputTuple,
      AlphaRegisteredEvent.OutputTuple,
      AlphaRegisteredEvent.OutputObject
    >;
    AlphaRegistered: TypedContractEvent<
      AlphaRegisteredEvent.InputTuple,
      AlphaRegisteredEvent.OutputTuple,
      AlphaRegisteredEvent.OutputObject
    >;

    "Subscribed(address,bytes32)": TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;
    Subscribed: TypedContractEvent<
      SubscribedEvent.InputTuple,
      SubscribedEvent.OutputTuple,
      SubscribedEvent.OutputObject
    >;

    "Unsubscribed(address,bytes32)": TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;
    Unsubscribed: TypedContractEvent<
      UnsubscribedEvent.InputTuple,
      UnsubscribedEvent.OutputTuple,
      UnsubscribedEvent.OutputObject
    >;
  };
}
