/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ReputationRegistry {
  export type DealRecordStruct = {
    alphaId: BytesLike;
    accepted: boolean;
    apyBps: BigNumberish;
    investmentWei: BigNumberish;
    feeEarnedWei: BigNumberish;
    timestamp: BigNumberish;
  };

  export type DealRecordStructOutput = [
    alphaId: string,
    accepted: boolean,
    apyBps: bigint,
    investmentWei: bigint,
    feeEarnedWei: bigint,
    timestamp: bigint
  ] & {
    alphaId: string;
    accepted: boolean;
    apyBps: bigint;
    investmentWei: bigint;
    feeEarnedWei: bigint;
    timestamp: bigint;
  };

  export type AlphaStatsStruct = {
    totalPitched: BigNumberish;
    totalAccepted: BigNumberish;
    totalInvestedWei: BigNumberish;
    totalFeesEarnedWei: BigNumberish;
    sumApyBps: BigNumberish;
    lastDealAt: BigNumberish;
  };

  export type AlphaStatsStructOutput = [
    totalPitched: bigint,
    totalAccepted: bigint,
    totalInvestedWei: bigint,
    totalFeesEarnedWei: bigint,
    sumApyBps: bigint,
    lastDealAt: bigint
  ] & {
    totalPitched: bigint;
    totalAccepted: bigint;
    totalInvestedWei: bigint;
    totalFeesEarnedWei: bigint;
    sumApyBps: bigint;
    lastDealAt: bigint;
  };
}

export interface ReputationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorized"
      | "getAvgApy"
      | "getDealHistory"
      | "getScore"
      | "getStats"
      | "owner"
      | "recordDeal"
      | "setAuthorized"
      | "stats"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AuthorizationSet" | "DealRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAvgApy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDealHistory",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "getScore", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "getStats", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDeal",
    values: [BytesLike, boolean, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setAuthorized",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "stats", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAvgApy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDealHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getScore", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getStats", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "recordDeal", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stats", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace AuthorizationSetEvent {
  export type InputTuple = [addr: AddressLike, auth: boolean];
  export type OutputTuple = [addr: string, auth: boolean];
  export interface OutputObject {
    addr: string;
    auth: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DealRecordedEvent {
  export type InputTuple = [
    alphaId: BytesLike,
    accepted: boolean,
    apyBps: BigNumberish,
    investmentWei: BigNumberish,
    feeWei: BigNumberish
  ];
  export type OutputTuple = [
    alphaId: string,
    accepted: boolean,
    apyBps: bigint,
    investmentWei: bigint,
    feeWei: bigint
  ];
  export interface OutputObject {
    alphaId: string;
    accepted: boolean;
    apyBps: bigint;
    investmentWei: bigint;
    feeWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReputationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReputationRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReputationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorized: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  getAvgApy: TypedContractMethod<[alphaId: BytesLike], [bigint], "view">;

  getDealHistory: TypedContractMethod<
    [alphaId: BytesLike],
    [ReputationRegistry.DealRecordStructOutput[]],
    "view"
  >;

  getScore: TypedContractMethod<[alphaId: BytesLike], [bigint], "view">;

  getStats: TypedContractMethod<
    [alphaId: BytesLike],
    [ReputationRegistry.AlphaStatsStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordDeal: TypedContractMethod<
    [
      alphaId: BytesLike,
      accepted: boolean,
      apyBps: BigNumberish,
      investmentWei: BigNumberish,
      feeEarnedWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setAuthorized: TypedContractMethod<
    [addr: AddressLike, auth: boolean],
    [void],
    "nonpayable"
  >;

  stats: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalPitched: bigint;
        totalAccepted: bigint;
        totalInvestedWei: bigint;
        totalFeesEarnedWei: bigint;
        sumApyBps: bigint;
        lastDealAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorized"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAvgApy"
  ): TypedContractMethod<[alphaId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDealHistory"
  ): TypedContractMethod<
    [alphaId: BytesLike],
    [ReputationRegistry.DealRecordStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getScore"
  ): TypedContractMethod<[alphaId: BytesLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStats"
  ): TypedContractMethod<
    [alphaId: BytesLike],
    [ReputationRegistry.AlphaStatsStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDeal"
  ): TypedContractMethod<
    [
      alphaId: BytesLike,
      accepted: boolean,
      apyBps: BigNumberish,
      investmentWei: BigNumberish,
      feeEarnedWei: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAuthorized"
  ): TypedContractMethod<
    [addr: AddressLike, auth: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stats"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint] & {
        totalPitched: bigint;
        totalAccepted: bigint;
        totalInvestedWei: bigint;
        totalFeesEarnedWei: bigint;
        sumApyBps: bigint;
        lastDealAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "AuthorizationSet"
  ): TypedContractEvent<
    AuthorizationSetEvent.InputTuple,
    AuthorizationSetEvent.OutputTuple,
    AuthorizationSetEvent.OutputObject
  >;
  getEvent(
    key: "DealRecorded"
  ): TypedContractEvent<
    DealRecordedEvent.InputTuple,
    DealRecordedEvent.OutputTuple,
    DealRecordedEvent.OutputObject
  >;

  filters: {
    "AuthorizationSet(address,bool)": TypedContractEvent<
      AuthorizationSetEvent.InputTuple,
      AuthorizationSetEvent.OutputTuple,
      AuthorizationSetEvent.OutputObject
    >;
    AuthorizationSet: TypedContractEvent<
      AuthorizationSetEvent.InputTuple,
      AuthorizationSetEvent.OutputTuple,
      AuthorizationSetEvent.OutputObject
    >;

    "DealRecorded(bytes32,bool,uint256,uint256,uint256)": TypedContractEvent<
      DealRecordedEvent.InputTuple,
      DealRecordedEvent.OutputTuple,
      DealRecordedEvent.OutputObject
    >;
    DealRecorded: TypedContractEvent<
      DealRecordedEvent.InputTuple,
      DealRecordedEvent.OutputTuple,
      DealRecordedEvent.OutputObject
    >;
  };
}
